title: Getting started with NeRu
description: Create and deploy a NeRu project.
products:
  - neru
languages: 
  - javascript

introduction:
  title: Introduction to this tutorial
  description: This tutorial will take you through creating and deploying a NeRu project.
  content: |
    # Introduction
    [NeRu](/neru/overview) allows you to create and deploy serverless backends for your Vonage Applications.

    This tutorial is a step-by-step guide showing you how to get started with one of the demo NeRu projects, a voice quiz.

prerequisites:
  - create-nexmo-account
  - install-nodejs

tasks:
  - neru/create-vonage-application
  - buy-nexmo-number
  - link-nexmo-number
  - neru/get-started/create-project
  - neru/get-started/deploy-project
  - neru/get-started/view-project

conclusion:
  title: What's next?
  description: What else can you do with NeRu?
  content: |

    # What's next?

    Try [debugging](/neru/debugging) your project locally, or view the other [NeRu tutorials](/neru/tutorials).